// Single source of truth for `data-testid` values used by production UI and
// browser/component tests. Keep IDs kebab-case and scoped by the user-facing
// feature so copy, translations, and DOM reshuffles do not break tests.

type NavigationSlug =
  | "accounts"
  | "budgets"
  | "dashboard"
  | "imports"
  | "recurring"
  | "reports"
  | "rules"
  | "sync"
  | "settings"
  | "transactions";
type SettingsRow = "active-ledger" | "active-role" | "sync-mode" | "theme-preference" | "workspace";
type StatusSurface = "drawer" | "settings";
type TransactionType = "expense" | "income" | "transfer";

export const testIds = {
  shell: {
    root: "fastifly-root",
    app: "app-shell",
    appBootstrap: "fastifly-app-bootstrap",
    main: "app-main",
    pendingSyncAlert: "pending-sync-alert",
    syncConflictAlert: "sync-conflict-alert",
    topBar: "top-bar",
    topBarTitle: "top-bar-title",
    breadcrumbsDesktop: "breadcrumbs-desktop",
    breadcrumbsMobile: "breadcrumbs-mobile",
    topBarStatus: "top-bar-status",
    topBarInternetStatus: "top-bar-internet-status",
    topBarAccountsStatus: "top-bar-accounts-status",
    topBarTransactionsStatus: "top-bar-transactions-status",
    themeToggleButton: "theme-toggle-button",
    authGate: "auth-gate-screen",
    authGateMessage: "auth-gate-message",
    updateAlert: "app-update-alert",
  },
  routes: {
    dashboardRoute: "route-dashboard",
    accountsRoute: "route-accounts",
    transactionsRoute: "route-transactions",
    budgetsRoute: "route-budgets",
    importsRoute: "route-imports",
    rulesRoute: "route-rules",
    recurringRoute: "route-recurring",
    reportsRoute: "route-reports",
    syncRoute: "route-sync",
    settingsRoute: "route-settings",
    loginRoute: "route-login",
  },
  icon: {
    brand: "fastifly-brand-icon",
  },
  navigation: {
    mobileTabbar: "mobile-tabbar",
    mobileMoreButton: "mobile-more-button",
    mobileMoreDrawer: "mobile-more-drawer",
    mobileMoreDrawerClose: "mobile-more-drawer-close",
    mobileMoreDrawerNav: "mobile-more-drawer-nav",
    mobileNav: (slug: NavigationSlug) => `mobile-nav-${slug}`,
    moreNav: (slug: NavigationSlug) => `more-nav-${slug}`,
    logoutButton: "logout-button",
  },
  auth: {
    page: "auth-page",
    panel: "auth-panel",
    title: "auth-title",
    description: "auth-description",
    form: "auth-credentials-form",
    usernameInput: "auth-username-input",
    usernameError: "auth-username-error",
    lockedUsername: "auth-locked-username",
    passwordInput: "auth-password-input",
    passwordError: "auth-password-error",
    errorAlert: "auth-error-alert",
    errorTitle: "auth-error-title",
    errorMessage: "auth-error-message",
    submitButton: "auth-submit-button",
    modeSwitchButton: "auth-mode-switch-button",
    demoLoginCard: "demo-login-card",
    demoLoginTitle: "demo-login-title",
    demoUsernameValue: "demo-username-value",
    demoPasswordValue: "demo-password-value",
    useDemoLoginButton: "use-demo-login-button",
    copyDemoUsernameButton: "copy-demo-username-button",
    copyDemoPasswordButton: "copy-demo-password-button",
    sessionExpired: {
      dialog: "session-expired-dialog",
      title: "session-expired-title",
      description: "session-expired-description",
      form: "session-expired-login-form",
      usernameInput: "session-expired-username-input",
      lockedUsername: "session-expired-locked-username",
      passwordInput: "session-expired-password-input",
      passwordError: "session-expired-password-error",
      errorAlert: "session-expired-error-alert",
      errorMessage: "session-expired-error-message",
      submitButton: "session-expired-submit-button",
      switchAccountButton: "session-expired-switch-account-button",
    },
  },
  dashboard: {
    page: "dashboard-page",
    netWorthCard: "dashboard-net-worth-card",
    netWorthLabel: "dashboard-net-worth-label",
    netWorthValue: "dashboard-net-worth-value",
    netWorthDescription: "dashboard-net-worth-description",
    summaryMetrics: "dashboard-summary-metrics",
    cashAndBankMetric: "dashboard-cash-and-bank-metric",
    liabilitiesMetric: "dashboard-liabilities-metric",
    monthlyMetrics: "dashboard-monthly-metrics",
    incomeMetric: "dashboard-income-metric",
    spendingMetric: "dashboard-spending-metric",
    aside: "dashboard-aside",
    accountBalances: "dashboard-account-balances",
    accountBalancesList: "account-balances-list",
    accountBalancesEmpty: "account-balances-empty",
  },
  transactions: {
    page: "transactions-page",
    filters: {
      accountSelect: "transactions-filter-account-select",
      panel: "transactions-filter-panel",
      resetButton: "transactions-filter-reset-button",
      statusSelect: "transactions-filter-status-select",
      typeGroup: "transactions-filter-type-group",
      typeOption: (type: string) => `transactions-filter-type-${type}`,
    },
    loadMoreButton: "transactions-load-more-button",
    retryButton: "transactions-retry-button",
    listPanel: "transactions-list-panel",
    listTitle: "transactions-list-title",
    listDescription: "transactions-list-description",
    viewAllButton: "transactions-view-all-button",
    list: "transactions-list",
    emptyState: "transactions-empty-state",
    emptyTitle: "transactions-empty-title",
    emptyBody: "transactions-empty-body",
    row: (id: string) => `transaction-row-${id}`,
    rowTitle: (id: string) => `transaction-row-${id}-title`,
    rowMeta: (id: string) => `transaction-row-${id}-meta`,
    rowAmount: (id: string) => `transaction-row-${id}-amount`,
  },
  accounts: {
    page: "accounts-page",
    list: "accounts-list",
    emptyState: "accounts-empty-state",
    create: {
      panel: "account-create-panel",
      title: "account-create-title",
      description: "account-create-description",
      openButton: "account-create-open-button",
      dialog: "account-create-dialog",
      dialogTitle: "account-create-dialog-title",
      dialogDescription: "account-create-dialog-description",
      form: "account-create-form",
      nameInput: "account-name-input",
      nameError: "account-name-error",
      typeSelect: "account-type-select",
      currencySelect: "account-currency-select",
      openingBalanceInput: "account-opening-balance-input",
      openingBalanceDateInput: "account-opening-balance-date-input",
      errorAlert: "account-create-error-alert",
      errorMessage: "account-create-error-message",
      successAlert: "account-create-success-alert",
      successMessage: "account-create-success-message",
      saveButton: "account-create-save-button",
    },
    archive: {
      button: (id: string) => `account-${id}-archive-button`,
      cancelButton: (id: string) => `account-${id}-archive-cancel-button`,
      confirmButton: (id: string) => `account-${id}-archive-confirm-button`,
      description: (id: string) => `account-${id}-archive-description`,
      dialog: (id: string) => `account-${id}-archive-dialog`,
      errorAlert: "account-archive-error-alert",
      errorMessage: "account-archive-error-message",
      successAlert: "account-archive-success-alert",
      successMessage: "account-archive-success-message",
      title: (id: string) => `account-${id}-archive-title`,
    },
    card: (id: string) => `account-card-${id}`,
    cardName: (id: string) => `account-card-${id}-name`,
    cardType: (id: string) => `account-card-${id}-type`,
    cardCurrency: (id: string) => `account-card-${id}-currency`,
    cardBalance: (id: string) => `account-card-${id}-balance`,
    balanceCard: (id: string) => `account-balance-card-${id}`,
    balanceName: (id: string) => `account-balance-card-${id}-name`,
    balanceKind: (id: string) => `account-balance-card-${id}-kind`,
    balanceAmount: (id: string) => `account-balance-card-${id}-amount`,
  },
  budgets: {
    page: "budgets-page",
    summary: "budget-summary",
    incomeMetric: "budget-income-metric",
    spendingMetric: "budget-spending-metric",
    availableMetric: "budget-available-metric",
    spendingRateMetric: "budget-spending-rate-metric",
    list: "budget-list",
    emptyState: "budget-empty-state",
    card: (id: string) => `budget-card-${id}`,
    cardName: (id: string) => `budget-card-${id}-name`,
    cardPeriod: (id: string) => `budget-card-${id}-period`,
    cardLimit: (id: string) => `budget-card-${id}-limit`,
    cardSpent: (id: string) => `budget-card-${id}-spent`,
    cardRemaining: (id: string) => `budget-card-${id}-remaining`,
    cardSpentRate: (id: string) => `budget-card-${id}-spent-rate`,
  },
  imports: {
    page: "imports-page",
    list: "imports-list",
    emptyState: "imports-empty-state",
    uploadButton: "imports-upload-button",
    commitButton: (id: string) => `imports-commit-${id}`,
    undoButton: (id: string) => `imports-undo-${id}`,
    card: (id: string) => `imports-card-${id}`,
    status: (id: string) => `imports-status-${id}`,
  },
  rules: {
    page: "rules-page",
    summary: "rules-summary",
    summaryTotal: "rules-summary-total",
    summaryEnabled: "rules-summary-enabled",
    summaryUpdated: "rules-summary-updated",
    quickGuide: "rules-quick-guide",
    loadError: "rules-load-error",
    retryButton: "rules-retry-button",
    feedbackAlert: "rules-feedback-alert",
    createForm: "rules-create-form",
    createNameInput: "rules-create-name-input",
    createStatusSelect: "rules-create-status-select",
    createEnabledSelect: "rules-create-enabled-select",
    createTypeSelect: "rules-create-type-select",
    createDescriptionInput: "rules-create-description-input",
    createAmountMinInput: "rules-create-amount-min-input",
    createAmountMaxInput: "rules-create-amount-max-input",
    createSubmitButton: "rules-create-submit-button",
    editButton: (id: string) => `rules-edit-${id}`,
    editListButton: (id: string) => `rules-list-edit-${id}`,
    cancelEditButton: (id: string) => `rules-edit-cancel-${id}`,
    saveEditButton: (id: string) => `rules-edit-save-${id}`,
    archiveButton: (id: string) => `rules-archive-${id}`,
    detailsButton: (id: string) => `rules-details-${id}`,
    editForm: (id: string) => `rules-edit-form-${id}`,
    editNameInput: (id: string) => `rules-edit-name-${id}`,
    editStatusSelect: (id: string) => `rules-edit-status-${id}`,
    editEnabledSelect: (id: string) => `rules-edit-enabled-${id}`,
    editTypeSelect: (id: string) => `rules-edit-type-${id}`,
    editDescriptionInput: (id: string) => `rules-edit-description-${id}`,
    editAmountMinInput: (id: string) => `rules-edit-amount-min-${id}`,
    editAmountMaxInput: (id: string) => `rules-edit-amount-max-${id}`,
    list: "rules-list",
    emptyState: "rules-empty-state",
    tabActive: "rules-tab-active",
    tabArchived: "rules-tab-archived",
    createButton: "rules-create-button",
    testButton: (id: string) => `rules-test-${id}`,
    applyButton: (id: string) => `rules-apply-${id}`,
    card: (id: string) => `rules-card-${id}`,
  },
  recurring: {
    page: "recurring-page",
    summary: "recurring-summary",
    summaryActive: "recurring-summary-active",
    summaryDueSoon: "recurring-summary-due-soon",
    summaryPaused: "recurring-summary-paused",
    list: "recurring-list",
    emptyState: "recurring-empty-state",
    createButton: "recurring-create-button",
    createDialog: "recurring-create-dialog",
    createForm: "recurring-create-form",
    createTypeSelect: "recurring-create-type-select",
    createTitleInput: "recurring-create-title-input",
    createDescriptionInput: "recurring-create-description-input",
    createDescriptionToggleButton: "recurring-create-description-toggle-button",
    createAmountInput: "recurring-create-amount-input",
    createCadenceSelect: "recurring-create-cadence-select",
    createNextRunInput: "recurring-create-next-run-input",
    createSourceAccountSelect: "recurring-create-source-account-select",
    createDestinationAccountSelect: "recurring-create-destination-account-select",
    createErrorAlert: "recurring-create-error-alert",
    createErrorMessage: "recurring-create-error-message",
    createGuardrailAlert: "recurring-create-guardrail-alert",
    createGuardrailMessage: "recurring-create-guardrail-message",
    createSuccessAlert: "recurring-create-success-alert",
    createSuccessMessage: "recurring-create-success-message",
    createSaveButton: "recurring-create-save-button",
    editButton: (id: string) => `recurring-edit-${id}`,
    toggleStatusButton: (id: string) => `recurring-toggle-status-${id}`,
    card: (id: string) => `recurring-card-${id}`,
    cardAmount: (id: string) => `recurring-card-${id}-amount`,
    cardNextRun: (id: string) => `recurring-card-${id}-next-run`,
    cardFlow: (id: string) => `recurring-card-${id}-flow`,
    cardStatus: (id: string) => `recurring-card-${id}-status`,
  },
  reports: {
    page: "reports-page",
    summary: "reports-summary",
    cashflowMetric: "reports-cashflow-metric",
    cashAndBankMetric: "reports-cash-and-bank-metric",
    liabilitiesMetric: "reports-liabilities-metric",
    accountsMetric: "reports-accounts-metric",
    incomeMetric: "reports-income-metric",
    spendingMetric: "reports-spending-metric",
    transferCountMetric: "reports-transfer-count-metric",
  },
  sync: {
    page: "sync-page",
    statusCard: "sync-status-card",
    conflictsCard: "sync-conflicts-card",
    openConflictCount: "sync-open-conflict-count",
    serverRevision: "sync-server-revision",
    lastOperationAt: "sync-last-operation-at",
    emptyConflicts: "sync-empty-conflicts",
    conflictRow: (id: string) => `sync-conflict-row-${id}`,
    conflictType: (id: string) => `sync-conflict-row-${id}-type`,
    conflictStatus: (id: string) => `sync-conflict-row-${id}-status`,
    conflictOperation: (id: string) => `sync-conflict-row-${id}-operation`,
  },
  settings: {
    page: "settings-page",
    overview: "settings-overview",
    appearance: "settings-appearance",
    themeLightButton: "settings-theme-light-button",
    themeDarkButton: "settings-theme-dark-button",
    themeSystemButton: "settings-theme-system-button",
    workspaceCard: "settings-workspace-card",
    automationCard: "settings-automation-card",
    syncHealthCard: "settings-sync-health-card",
    maintenanceCard: "settings-maintenance-card",
    sessionCard: "settings-session-card",
    diagnosticsCard: "settings-diagnostics-card",
    copyDiagnosticsButton: "settings-copy-diagnostics-button",
    copyDiagnosticsMessage: "settings-copy-diagnostics-message",
    copyWorkspaceIdButton: "settings-copy-workspace-id-button",
    copyLedgerIdButton: "settings-copy-ledger-id-button",
    logoutButton: "settings-logout-button",
    row: (slug: SettingsRow) => `settings-row-${slug}`,
    rowLabel: (slug: SettingsRow) => `settings-row-${slug}-label`,
    rowValue: (slug: SettingsRow) => `settings-row-${slug}-value`,
    systemStatus: "system-status",
  },
  runtimeStatus: {
    group: (surface: StatusSurface) => `runtime-status-${surface}`,
    internet: (surface: StatusSurface) => `runtime-status-${surface}-internet`,
    openConflicts: (surface: StatusSurface) => `runtime-status-${surface}-open-conflicts`,
    server: (surface: StatusSurface) => `runtime-status-${surface}-server`,
    savingChanges: (surface: StatusSurface) => `runtime-status-${surface}-saving-changes`,
  },
  transactionCreate: {
    panel: "transaction-create-panel",
    title: "transaction-create-title",
    description: "transaction-create-description",
    actions: "transaction-create-actions",
    quickButton: (type: TransactionType) => `quick-create-${type}-button`,
    unavailableAlert: "transaction-create-unavailable-alert",
    successAlert: "transaction-create-success-alert",
    successMessage: "transaction-create-success-message",
    dialog: "transaction-create-dialog",
    dialogTitle: "transaction-create-dialog-title",
    dialogDescription: "transaction-create-dialog-description",
    form: "transaction-create-form",
    amountInput: "transaction-amount-input",
    amountError: "transaction-amount-error",
    dateInput: "transaction-date-input",
    dateError: "transaction-date-error",
    sourceAccountSelect: "transaction-source-account-select",
    sourceAccountError: "transaction-source-account-error",
    destinationAccountSelect: "transaction-destination-account-select",
    destinationAccountError: "transaction-destination-account-error",
    descriptionInput: "transaction-description-input",
    descriptionError: "transaction-description-error",
    errorAlert: "transaction-create-error-alert",
    errorMessage: "transaction-create-error-message",
    saveButton: "transaction-save-button",
  },
} as const;
