// Single source of truth for `data-testid` values used by production UI and
// browser/component tests. Keep IDs kebab-case and scoped by the user-facing
// feature so copy, translations, and DOM reshuffles do not break tests.

type NavigationSlug =
  | "accounts"
  | "budgets"
  | "dashboard"
  | "reports"
  | "settings"
  | "transactions";
type SettingsRow = "active-ledger" | "sync-mode" | "theme-preference" | "workspace";
type StatusSurface = "drawer" | "settings";
type TransactionType = "expense" | "income" | "transfer";

export const testIds = {
  shell: {
    root: "fastifly-root",
    app: "app-shell",
    main: "app-main",
    pendingSyncAlert: "pending-sync-alert",
    topBar: "top-bar",
    topBarTitle: "top-bar-title",
    topBarStatus: "top-bar-status",
    topBarInternetStatus: "top-bar-internet-status",
    topBarAccountsStatus: "top-bar-accounts-status",
    topBarTransactionsStatus: "top-bar-transactions-status",
    themeToggleButton: "theme-toggle-button",
    authGate: "auth-gate-screen",
    authGateMessage: "auth-gate-message",
  },
  icon: {
    brand: "fastifly-brand-icon",
  },
  navigation: {
    mobileTabbar: "mobile-tabbar",
    mobileMoreButton: "mobile-more-button",
    mobileMoreDrawer: "mobile-more-drawer",
    mobileMoreDrawerClose: "mobile-more-drawer-close",
    mobileMoreDrawerNav: "mobile-more-drawer-nav",
    mobileNav: (slug: NavigationSlug) => `mobile-nav-${slug}`,
    moreNav: (slug: NavigationSlug) => `more-nav-${slug}`,
    logoutButton: "logout-button",
  },
  auth: {
    page: "auth-page",
    panel: "auth-panel",
    title: "auth-title",
    description: "auth-description",
    form: "auth-credentials-form",
    usernameInput: "auth-username-input",
    usernameError: "auth-username-error",
    lockedUsername: "auth-locked-username",
    passwordInput: "auth-password-input",
    passwordError: "auth-password-error",
    errorAlert: "auth-error-alert",
    errorTitle: "auth-error-title",
    errorMessage: "auth-error-message",
    submitButton: "auth-submit-button",
    modeSwitchButton: "auth-mode-switch-button",
    demoLoginCard: "demo-login-card",
    demoLoginTitle: "demo-login-title",
    demoUsernameValue: "demo-username-value",
    demoPasswordValue: "demo-password-value",
    useDemoLoginButton: "use-demo-login-button",
    copyDemoUsernameButton: "copy-demo-username-button",
    copyDemoPasswordButton: "copy-demo-password-button",
    sessionExpired: {
      dialog: "session-expired-dialog",
      title: "session-expired-title",
      description: "session-expired-description",
      form: "session-expired-login-form",
      usernameInput: "session-expired-username-input",
      lockedUsername: "session-expired-locked-username",
      passwordInput: "session-expired-password-input",
      passwordError: "session-expired-password-error",
      errorAlert: "session-expired-error-alert",
      errorMessage: "session-expired-error-message",
      submitButton: "session-expired-submit-button",
      switchAccountButton: "session-expired-switch-account-button",
    },
  },
  dashboard: {
    page: "dashboard-page",
    netWorthCard: "dashboard-net-worth-card",
    netWorthLabel: "dashboard-net-worth-label",
    netWorthValue: "dashboard-net-worth-value",
    netWorthDescription: "dashboard-net-worth-description",
    summaryMetrics: "dashboard-summary-metrics",
    cashAndBankMetric: "dashboard-cash-and-bank-metric",
    liabilitiesMetric: "dashboard-liabilities-metric",
    monthlyMetrics: "dashboard-monthly-metrics",
    incomeMetric: "dashboard-income-metric",
    spendingMetric: "dashboard-spending-metric",
    aside: "dashboard-aside",
    accountBalances: "dashboard-account-balances",
    accountBalancesList: "account-balances-list",
    accountBalancesEmpty: "account-balances-empty",
  },
  transactions: {
    page: "transactions-page",
    listPanel: "transactions-list-panel",
    listTitle: "transactions-list-title",
    listDescription: "transactions-list-description",
    viewAllButton: "transactions-view-all-button",
    list: "transactions-list",
    emptyState: "transactions-empty-state",
    emptyTitle: "transactions-empty-title",
    emptyBody: "transactions-empty-body",
    row: (id: string) => `transaction-row-${id}`,
    rowTitle: (id: string) => `transaction-row-${id}-title`,
    rowMeta: (id: string) => `transaction-row-${id}-meta`,
    rowAmount: (id: string) => `transaction-row-${id}-amount`,
  },
  accounts: {
    page: "accounts-page",
    list: "accounts-list",
    emptyState: "accounts-empty-state",
    card: (id: string) => `account-card-${id}`,
    cardName: (id: string) => `account-card-${id}-name`,
    cardType: (id: string) => `account-card-${id}-type`,
    cardCurrency: (id: string) => `account-card-${id}-currency`,
    cardBalance: (id: string) => `account-card-${id}-balance`,
    balanceCard: (id: string) => `account-balance-card-${id}`,
    balanceName: (id: string) => `account-balance-card-${id}-name`,
    balanceKind: (id: string) => `account-balance-card-${id}-kind`,
    balanceAmount: (id: string) => `account-balance-card-${id}-amount`,
  },
  budgets: {
    page: "budgets-page",
    summary: "budget-summary",
    incomeMetric: "budget-income-metric",
    spendingMetric: "budget-spending-metric",
    availableMetric: "budget-available-metric",
    spendingRateMetric: "budget-spending-rate-metric",
  },
  reports: {
    page: "reports-page",
    summary: "reports-summary",
    cashflowMetric: "reports-cashflow-metric",
    cashAndBankMetric: "reports-cash-and-bank-metric",
    liabilitiesMetric: "reports-liabilities-metric",
    accountsMetric: "reports-accounts-metric",
    incomeMetric: "reports-income-metric",
    spendingMetric: "reports-spending-metric",
    transferCountMetric: "reports-transfer-count-metric",
  },
  settings: {
    page: "settings-page",
    overview: "settings-overview",
    row: (slug: SettingsRow) => `settings-row-${slug}`,
    rowLabel: (slug: SettingsRow) => `settings-row-${slug}-label`,
    rowValue: (slug: SettingsRow) => `settings-row-${slug}-value`,
    systemStatus: "system-status",
  },
  runtimeStatus: {
    group: (surface: StatusSurface) => `runtime-status-${surface}`,
    internet: (surface: StatusSurface) => `runtime-status-${surface}-internet`,
    server: (surface: StatusSurface) => `runtime-status-${surface}-server`,
    savingChanges: (surface: StatusSurface) => `runtime-status-${surface}-saving-changes`,
  },
  transactionCreate: {
    panel: "transaction-create-panel",
    title: "transaction-create-title",
    description: "transaction-create-description",
    actions: "transaction-create-actions",
    quickButton: (type: TransactionType) => `quick-create-${type}-button`,
    unavailableAlert: "transaction-create-unavailable-alert",
    successAlert: "transaction-create-success-alert",
    successMessage: "transaction-create-success-message",
    dialog: "transaction-create-dialog",
    dialogTitle: "transaction-create-dialog-title",
    dialogDescription: "transaction-create-dialog-description",
    form: "transaction-create-form",
    amountInput: "transaction-amount-input",
    amountError: "transaction-amount-error",
    dateInput: "transaction-date-input",
    dateError: "transaction-date-error",
    sourceAccountSelect: "transaction-source-account-select",
    sourceAccountError: "transaction-source-account-error",
    destinationAccountSelect: "transaction-destination-account-select",
    destinationAccountError: "transaction-destination-account-error",
    descriptionInput: "transaction-description-input",
    descriptionError: "transaction-description-error",
    errorAlert: "transaction-create-error-alert",
    errorMessage: "transaction-create-error-message",
    saveButton: "transaction-save-button",
  },
} as const;
